init increment-15
AlekseyKas/metrics pull request #12
Opened 2022-08-10 07:18 UTC by AlekseyKas

#11

2022-08-15 10:04 UTC, Bazys requested changes
у нас по структуре есть каталог internal
предлагаю в него перенести 
- helpers
- database
- handlers
а каталог profiles в корень - там просто инфа

2022-08-15 14:10 UTC, Bazys commented
заведи себе привычку (или настрой githooks) перед отправкой на ревью делать `golangci-lint run ./...`
пример .golangci.yaml
```.golangci.yaml
run:
  skip-files:
    - "mocks\\.go$"
  skip-dirs:
    - assets
    - build
    - test
  tests: false
  concurrency: 4

# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs:
          - printf
          - debugf
          - infof
          - warnf
          - errorf
          - fatalf
          - wrapf
          - fieldalignment
  gocyclo:
    min-complexity: 25
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  misspell:
    locale: US
  unparam:
    check-exported: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - deadcode
    - revive
    - gosec
    - unconvert
    - goconst
    - misspell
    - unparam
    - prealloc
    - exportloopref
    - gochecknoinits
    - gocritic
    - dupl
    - gocyclo
    - goimports
    - ineffassign
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint

  max-per-linter: 0
  max-same-issues: 0
  new: false
```
очень часто не проверяешь возвращаемые ошибки.

2022-08-15 19:18 UTC, Bazys commented
не проходит тест
```
time="2022-08-15T22:16:59+03:00" level=error msg="Error connection to DB: FATAL: database \"praktikum\" does not exist (SQLSTATE 3D000)"
FAIL    github.com/AlekseyKas/metrics/internal/server/database  0.557s

```

2022-08-16 07:45 UTC, AlekseyKas commented
Пока тесты базы пакета database убрал (буду их переделывать с mock). И с golangci-lint исправил все ошибки. Спасибо

2022-08-16 09:51 UTC, Bazys approved these changes
Есть несколько замечаний, но они относятся больше к предыдущим инкриментам, поэтому из-за них не буду возвращать. Но все таки хотелось бы что исправил в спокойном режиме.

2022-08-16 09:51 UTC, Bazys commented on cmd/server/main.go
>  	go waitSignals(cancel)
обычно всё таки передают контекст с отменой, а не саму функцию отмены.

2022-08-16 09:51 UTC, Bazys commented on cmd/server/main.go
>  			logrus.Error("Connection to postrgres faild: ", err)
кстати, это одно из тех редких мест, где можно паниковать.
Ведь если приложение не смогло получить доступ к БД, то он и не сможет выполнять своё предназначение.

2022-08-16 09:51 UTC, Bazys commented on internal/storage/storage.go
>  	MM        map[string]interface{}
нам точно нужно делать публичным эту мапу?
мы ведь ее все время мьютексами защищаем. А так раз и снаружи изменили.

2022-08-16 09:51 UTC, Bazys commented on internal/storage/storage.go
>  func (m *MetricsStore) InitDB(jm []JSONMetrics) error {
посмотри всё таки в сторону нормальных миграторов, типа:
1. https://github.com/golang-migrate/migrate
2. https://github.com/pressly/goose

2022-08-16 09:51 UTC, Bazys commented on internal/server/database/database.go
> +	err := Conn.Close()
вот здесь достаточно просто вернуть ошибку, а логирование делать где то в одном месте
```suggestion
	return Conn.Close()
```

2022-08-16 09:51 UTC, Bazys commented on internal/server/database/database.go
>  var Conn *pgx.Conn
завернуть *pgx.Conn в структуру и сделать методы для этой структуры?
и заодно избавишься от публичной переменной.

2022-08-16 11:54 UTC, AlekseyKas commented on cmd/server/main.go
>  	go waitSignals(cancel)
Не совсем понял для чего в этой рутине нужен контекст.

2022-08-16 11:57 UTC, AlekseyKas commented on cmd/server/main.go
>  			logrus.Error("Connection to postrgres faild: ", err)
поправил

2022-08-16 12:00 UTC, AlekseyKas commented on internal/storage/storage.go
>  	MM        map[string]interface{}
Я сделал её публичной , т.к. инициализирую хранилище метрик в main: 
func main() {
	// Inint storage server
	s := &storage.MetricsStore{
		MM: structs.Map(storage.Metrics{}),
	}

2022-08-17 15:46 UTC, merged